### ISSUE TITLE
button: babel error when compiling

### ISSUE THREAD

**Issue by bressain** [pluralsight/design-system#120]
### Expected behavior

No babel compilation errors

### Actual behavior

Babel compile fails:

```
ERROR in ./node_modules/@pluralsight/ps-design-system-button/react.js
Module build failed: ReferenceError: Unknown plugin "glamorous-displayname" specified in "/Users/bressain/code/ps/channels/client/node_modules/@pluralsight/ps-design-system-button/.babelrc" at 0, attempted to resolve relative to "/Users/bressain/code/ps/channels/client/node_modules/@pluralsight/ps-design-system-button"
    at /Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/Users/bressain/code/ps/channels/client/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/bressain/code/ps/channels/client/node_modules/babel-loader/lib/index.js:49:20)
    at Object.module.exports (/Users/bressain/code/ps/channels/client/node_modules/babel-loader/lib/index.js:174:20)
 @ ./src/secret-page/index.js 18:0-64
 @ ./src/router.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://0.0.0.0:3000 ./src/index.js
```
Looks like the `.babelrc` file was included in the package and maybe shouldn't?

### Steps to repro

1. Add the 8.1.0 button to your project. See the error when webpacking or running babel

### Related packages

- button@8.1.0

### Environment

- OS - MacOS 10.12
- Browser version - Chrome v61

**Comment by KaidenR** [comment]
This is also happening in the latest version of the card component (`6.0.5`) and Is making it so we cannot upgrade.

**Comment by jaketrent** [comment]
@bressain button@8.1.1 should fix this.  Please let me know how it goes.

**Comment by jaketrent** [comment]
@KaidenR card@6.0.6 should fix this.  Please let me know how it goes.

**Comment by bressain** [comment]
Latest change fixed the compile error 👍
