### ISSUE TITLE
starrating: Unknown event handler property errors 

### ISSUE THREAD

**Issue by willsoto** [pluralsight/design-system#1606]
### Expected behavior

Components should not warn about unknown properties when used with React 17 (pretty sure this is a React 17 issue but it could also apply to 16)

### Actual behavior

```
  console.error
    Warning: Unknown event handler property `onEnter`. It will be ignored.
        at button
        at Star (/Users/will/code/ps-dev/Projects-UI/node_modules/@pluralsight/ps-design-system-starrating/src/react/star.tsx:96:3)
        at div
        at /Users/will/code/ps-dev/Projects-UI/node_modules/@pluralsight/ps-design-system-starrating/src/react/index.tsx:41:6
        at div
        at div
        at ProjectFeedback (/Users/will/code/ps-dev/Projects-UI/src/build/subproject-recap/project-feedback.tsx:33:11)
        at withCreateFeedback(ProjectFeedback) (/Users/will/code/ps-dev/Projects-UI/src/build/common/create-feedback/component.tsx:56:38)
        at div
        at div
        at div
        at SubprojectRecap (/Users/will/code/ps-dev/Projects-UI/src/build/subproject-recap/component.tsx:28:5)
        at div
        at Card (/Users/will/code/ps-dev/Projects-UI/node_modules/reactstrap/lib/Card.js:35:25)
        at BuildContainer (/Users/will/code/ps-dev/Projects-UI/src/build/build-container.tsx:72:5)
        at section
        at div
        at div
        at BuildPage (/Users/will/code/ps-dev/Projects-UI/src/build/page.tsx:31:18)
        at Route (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router/cjs/react-router.js:470:29)
        at Switch (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router/cjs/react-router.js:676:29)
        at Router (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router/cjs/react-router.js:99:30)
        at BrowserRouter (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router-dom/cjs/react-router-dom.js:67:35)
        at ApolloProvider (/Users/will/code/ps-dev/Projects-UI/node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
        at Providers (/Users/will/code/ps-dev/Projects-UI/test-utils/render.tsx:28:11)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3448:9)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
```

```
  console.error
    Warning: Unknown event handler property `onLeave`. It will be ignored.
        at button
        at Star (/Users/will/code/ps-dev/Projects-UI/node_modules/@pluralsight/ps-design-system-starrating/src/react/star.tsx:96:3)
        at div
        at /Users/will/code/ps-dev/Projects-UI/node_modules/@pluralsight/ps-design-system-starrating/src/react/index.tsx:41:6
        at div
        at div
        at ProjectFeedback (/Users/will/code/ps-dev/Projects-UI/src/build/subproject-recap/project-feedback.tsx:33:11)
        at withCreateFeedback(ProjectFeedback) (/Users/will/code/ps-dev/Projects-UI/src/build/common/create-feedback/component.tsx:56:38)
        at div
        at div
        at div
        at SubprojectRecap (/Users/will/code/ps-dev/Projects-UI/src/build/subproject-recap/component.tsx:28:5)
        at div
        at Card (/Users/will/code/ps-dev/Projects-UI/node_modules/reactstrap/lib/Card.js:35:25)
        at BuildContainer (/Users/will/code/ps-dev/Projects-UI/src/build/build-container.tsx:72:5)
        at section
        at div
        at div
        at BuildPage (/Users/will/code/ps-dev/Projects-UI/src/build/page.tsx:31:18)
        at Route (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router/cjs/react-router.js:470:29)
        at Switch (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router/cjs/react-router.js:676:29)
        at Router (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router/cjs/react-router.js:99:30)
        at BrowserRouter (/Users/will/code/ps-dev/Projects-UI/node_modules/react-router-dom/cjs/react-router-dom.js:67:35)
        at ApolloProvider (/Users/will/code/ps-dev/Projects-UI/node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
        at Providers (/Users/will/code/ps-dev/Projects-UI/test-utils/render.tsx:28:11)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at validateProperty$1 (node_modules/react-dom/cjs/react-dom.development.js:3448:9)
      at warnUnknownProperties (node_modules/react-dom/cjs/react-dom.development.js:3559:21)
      at validateProperties$2 (node_modules/react-dom/cjs/react-dom.development.js:3583:3)
      at validatePropertiesInDevelopment (node_modules/react-dom/cjs/react-dom.development.js:8765:5)
      at setInitialProperties (node_modules/react-dom/cjs/react-dom.development.js:9041:5)
```

### Steps to repro

1. Use the component as described in the [docs](https://design-system.pluralsight.com/components/starrating#star-rating) with React 17
2. Check console for errors

### Related packages

- "@pluralsight/ps-design-system-starrating": "~7.3.16",

### Environment

- OS - MacOS 10.12
- Browser version - FF 85

**Comment by EdwardIrby** [comment]
resolved in #1562
