### ISSUE TITLE
<Global>: Can't run bootstrap

### ISSUE THREAD

**Issue by TravisBumgarner** [pluralsight/design-system#350]
## Bug

When running `npm run bootstrap` I get the following error:

```
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
```

And here is the output from running bootstrap onward:

```
(3971) >> npm run bootstrap

> design-system@1.0.0 bootstrap /Users/travisbumgarner/Documents/programming/design-system
> lerna bootstrap --hoist

lerna notice cli v3.4.3
lerna info versioning independent
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-row -> @pluralsight/ps-design-system-drawer
lerna WARN ECYCLE @pluralsight/ps-design-system-site -> @pluralsight/ps-design-system-row -> @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-row -> @pluralsight/ps-design-system-row@^2.6.22
lerna WARN ECYCLE @pluralsight/ps-design-system-row -> @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-row
lerna WARN ECYCLE @pluralsight/ps-design-system-site -> @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-row -> @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-drawer@^1.5.9
lerna WARN ECYCLE @pluralsight/ps-design-system-table -> @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-row -> @pluralsight/ps-design-system-drawer -> @pluralsight/ps-design-system-drawer@^1.5.9
lerna info Bootstrapping 41 packages
lerna WARN EHOIST_ROOT_VERSION The repository root depends on webpack@^4.0.0, which differs from the more common webpack@^3.6.0.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-site" package depends on webpack@^3.6.0, which differs from the hoisted webpack@^4.0.0.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-errors" package depends on react@^16.4.2, which differs from the hoisted react@^16.2.0.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-errors" package depends on react-dom@^16.4.2, which differs from the hoisted react-dom@^16.2.0.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-switch" package depends on react-dom@^16.6.3, which differs from the hoisted react-dom@^16.2.0.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-drawer" package depends on babel-cli@^6.25.0, which differs from the hoisted babel-cli@^6.24.1.
lerna WARN EHOIST_PKG_VERSION "packages-api" package depends on babel-cli@^6.26.0, which differs from the hoisted babel-cli@^6.24.1.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-link" package depends on prop-types@^15.6.0, which differs from the hoisted prop-types@^15.5.10.
lerna WARN EHOIST_PKG_VERSION "@pluralsight/ps-design-system-site" package depends on prop-types@^15.5.9, which differs from the hoisted prop-types@^15.5.10.
lerna WARN EHOIST_PKG_VERSION "packages-api" package depends on dotenv@^4.0.0, which differs from the hoisted dotenv@^5.0.1.
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna info hoist Finished bootstrapping root
lerna info Symlinking packages and binaries
lerna info lifecycle @pluralsight/ps-design-system-storybook-addon-center@1.0.3~prepublish: @pluralsight/ps-design-system-storybook-addon-center@1.0.3
lerna info lifecycle @pluralsight/ps-design-system-theme@1.4.1~prepublish: @pluralsight/ps-design-system-theme@1.4.1

> @pluralsight/ps-design-system-storybook-addon-center@1.0.3 prepublish /Users/travisbumgarner/Documents/programming/design-system/packages/storybook-addon-center
> npm run build


> @pluralsight/ps-design-system-storybook-addon-center@1.0.3 build /Users/travisbumgarner/Documents/programming/design-system/packages/storybook-addon-center
> babel src --out-dir dist --ignore spec.js

src/index.js -> dist/index.js

> @pluralsight/ps-design-system-theme@1.4.1 prepublish /Users/travisbumgarner/Documents/programming/design-system/packages/theme
> npm run build


> @pluralsight/ps-design-system-theme@1.4.1 build /Users/travisbumgarner/Documents/programming/design-system/packages/theme
> babel src --out-dir dist --ignore spec.js --copy-files

src/react/index.js -> dist/react/index.js
src/react/with-theme.js -> dist/react/with-theme.js
src/vars/index.js -> dist/vars/index.js
lerna info lifecycle @pluralsight/ps-design-system-core@4.3.6~prepublish: @pluralsight/ps-design-system-core@4.3.6

> @pluralsight/ps-design-system-core@4.3.6 prepublish /Users/travisbumgarner/Documents/programming/design-system/packages/core
> npm run build


> @pluralsight/ps-design-system-core@4.3.6 build /Users/travisbumgarner/Documents/programming/design-system/packages/core
> node ./build

/Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/utils/args.js:9
  var args = func.toString().match(/function\s.*?\(([^)]*)\)/)[1];
                                                              ^

TypeError: Cannot read property '1' of null
    at module.exports (/Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/utils/args.js:9:63)
    at processExports (/Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/index.js:61:29)
    at processExports (/Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/index.js:82:25)
    at /Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/index.js:137:23
    at Array.forEach (<anonymous>)
    at processExports (/Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/index.js:132:6)
    at module.exports (/Users/travisbumgarner/Documents/programming/design-system/node_modules/promisify-node/index.js:164:10)
/**
    at Object.<anonymous> (/Users/travisbumgarner/Documents/programming/design-system/packages/build/postcss/transform.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pluralsight/ps-design-system-core@4.3.6 build: `node ./build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @pluralsight/ps-design-system-core@4.3.6 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/travisbumgarner/.npm/_logs/2018-11-20T22_29_27_109Z-debug.log
lerna info lifecycle @pluralsight/ps-design-system-core@4.3.6~prepublish: Failed to exec prepublish script
lerna ERR! lifecycle "prepublish" errored in "@pluralsight/ps-design-system-core", exiting 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! design-system@1.0.0 bootstrap: `lerna bootstrap --hoist`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the design-system@1.0.0 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/travisbumgarner/.npm/_logs/2018-11-20T22_29_27_283Z-debug.log
```

### Steps to repro

1. Clone repo
2. Run `nvm use`
3. Run `npm install`
4. Run `npm run bootstrap`

### Environment

- OS - MacOS 10.13.6 (Macbook Air personal computer, I also got this on my work computer)

### Desired behavior

I found this, which works but doesn't seem like the best solution: https://github.com/askmike/gekko/issues/2150#issuecomment-387944721

**Comment by danethurber** [comment]
@TravisBumgarner can you try to completely remove all the node_modules and then try your steps again

`npm run clean`
`rm -rf node_module`

**Comment by TravisBumgarner** [comment]
Just did a fresh git clone and bootstrap and it seems to be working now. 👍
